[package]
name = "ribbons"
version = "0.1.0"
entrypoint = "/src/ribbons.typ"
authors = ["@solstice23"]
license = "MIT"
description = "Create Sankey and Chord (ribbon-like) diagrams."
repository = "https://github.com/solstice23/typst-ribbons"
keywords = ["sankey", "chord", "diagram", "visualization", "ribbon"]
categories = ["visualization"]
exclude = [
	"docs",
	"gallery",
	"test"
]